name: Trixie build
on:
  push:
    branches:
      - trixie
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [32, 64]
        build_type: [basic]
        include:
          - arch: 32
            build_type: basic
            os: ubuntu-24.04-arm
          - arch: 64
            build_type: basic
            os: ubuntu-24.04-arm

      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set env variabiles
        run: |
          echo ARTIFACT_NAME=kuiper_"${{ matrix.build_type }}"_"${{ matrix.arch }}" >> $GITHUB_ENV
          if [ "${{ matrix.arch }}" == "64" ]; then
            sed -i 's/^TARGET_ARCHITECTURE=armhf/TARGET_ARCHITECTURE=arm64/' config
          fi
      - name: Build image
        run: |
          sudo bash build-docker.sh
          ls kuiper-volume/*.zip >/dev/null 2>&1 && exit 0 || exit 2
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}_image
          path: ${{ github.workspace }}/kuiper-volume/*.zip
      - name: Upload meta
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}_meta
          path: |
            ${{ github.workspace }}/kuiper-volume
            !${{ github.workspace }}/kuiper-volume/*.zip
